### ISSUE TITLE
[meta] transition doc. to CR at W3C

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#308]
Planning bug for CR. 

For all requests to advance a specification to a new maturity level other than Note the Working Group:

* [ ] must record the group's decision to request advancement.
* [ ] must obtain Director approval.
* [ ] must provide public documentation of all substantive changes to the technical report since the previous publication.
* [ ] must formally address all issues raised about the document since the previous maturity level.
* [ ] must provide public documentation of any Formal Objections.
* [ ] should provide public documentation of changes that are not substantive.
* [ ] should report which, if any, of the Working Group's requirements for this document have changed since the previous step.
* [ ] should report any changes in dependencies with other groups.
* [x] should provide information about implementations known to the Working Group. **Provided at top of document**. 

To publish a Candidate recommendation, in addition to meeting the general requirements for advancement a Working Group:

* [ ] must show that the specification has met all Working Group requirements, or explain why the requirements have changed or been deferred,
* [ ] must document changes to dependencies during the development of the specification,
* [ ] must document how adequate implementation experience will be demonstrated,
* [ ] must specify the deadline for comments, which must be at least four weeks after publication, and should be longer for complex documents,
* [ ] must show that the specification has received wide review, and
* [ ] may identify features in the document as "at risk". These features may be removed before advancement to Proposed Recommendation without a requirement to publish a new Candidate Recommendation.

**Comment by marcoscaceres** [comment]
Unfortunately, the W3C won't support live updates to CR documents - so, it's pointless to go through this. I'm going to record in that the spec is ready to implement, but keep the document as a WD. Once we have 2 interoperable implementations and the spec is long done, we can hand the spec over to the W3C to appease the patent lawyers and government officials.
