### ISSUE TITLE
Include Minimal Store/Catalog MetaData in Manifest

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#448]
GOAL: Minimize work for Web App Developers to publish/list their apps in app stores/catalogs

PROPOSAL: @RobDolinMS is working on an analysis of minimal app store MetaData to publish and app and will propose additions to the Web App Manifest.  
- [x] #435 Add description member
- [x] #476 / #497 Developer info and/or unique ID - so a web app can be mapped to a developer
- [x] #477 / #490 Screenshots - have not found a store/catalog that does not require screenshot(s)
- [x] #523 / #567 IARC Rating - so a web app can indicate their age ratings
- [x] #569 App Category - so a web app developer can communicate desired app category

FAQ: 
Q: How do web app developers update their app store metadata if it has been read from a Web App Manifest?
A: App stores/catalogs SHOULD either:
1. Use data in the Web App Manifest as the primary source of truth (if available) and make any data shown in the app store UI as read-only (Preferred)
2. Enable one-time import of data from the Web App Manifest and make it clear to app developers that they MUST edit their app metadata via the app store UI

**Comment by marcoscaceres** [comment]
Sent a PR for #435

**Comment by marcoscaceres** [comment]
@RobDolinMS, ping.

**Comment by marcoscaceres** [comment]
Closing for now... @RobDolinMS, kindly reopen the issue when you want to proceed.

**Comment by RobDolinMS** [comment]
@marcoscaceres - I'm back from some travel and meeting with some folks from the Edge team today.  Would you please re-open (as I don't seem to have permissions to be able to do so.)  Thanks.

**Comment by marcoscaceres** [comment]
Good to have you back! 😃

**Comment by marcoscaceres** [comment]
Screenshot may be related to https://github.com/w3c/manifest/issues/361 as those screenshots might be platform specific in some cases.

**Comment by christianliebel** [comment]
`categories` and `iarc_rating_id` have been added in the meantime, so I guess we can close this.

**Comment by aarongustafson** [comment]
Thanks for the heads-up @christianliebel!
