### ISSUE TITLE
Create test suite to check Web App Manifest feature support

### ISSUE THREAD

**Issue by tomayac** [w3c/manifest#666]
The core issue is that most features come to play only after the “add to home screen” step, i.e., require manual interaction with a browser first, and then manual review with the operating system (e.g., verify which icon was used on the home screen) and other apps (e.g., verify if the scope is respected). A first stab at the most basic level (initially focused on iOS but useful on other platforms as well) is https://ios-a2hs-demo.glitch.me/, but many questions remain. 

# Checklist

**Tested:**
- [x] display
- [x] icons
- [x] name
- [x] orientation
- [x] short_name
- [x] theme_color
- [x] shortcuts (https://github.com/web-platform-tests/wpt/pull/24452)
- [x] shortcuts / icons CORS & CSP (https://github.com/web-platform-tests/wpt/pull/27620)
- [x] icons / CORS & CSP (https://github.com/web-platform-tests/wpt/pull/27620)
- [ ] scope
- [x] start_url
- [ ] dir
- [ ] lang

HTML: https://github.com/web-platform-tests/wpt/issues/24389

**Not testing for now:**
- description (moved to Manifest App Info, #900)
- categories (moved to Manifest App Info, #900)
- screenshots (moved to Manifest App Info, #900)
- iarc_rating_id (moved to Manifest App Info, #900)
- related_applications (currently single-engine, #950)
- prefer_related_applications (currently single-engine, #950)
- icons/monochrome purpose (currently single-engine, #905)

**Results sheet:**
https://docs.google.com/spreadsheets/d/1_Ts5r4WksveBivvQ_KjdBrSDHDmNpNWqiER019A1onM/edit?usp=sharing

**Comment by tomayac** [comment]
Also see this [Twitter thread](http://twitter.com/tomayac/status/986997823169277952) for further background.

**Comment by marcoscaceres** [comment]
All interested folks: should we have a call about how we should do the testing? I have ideas, but want to make sure we are all on the same page. 

@honry, you'd made a start on some of this already (on the API side, at least). However, we want to start just by testing and validating the manifest properties as manual tests.

**Comment by Honry** [comment]
@marcoscaceres, I'm really interested in your ideas. 

Test automation is an ultimate goal, and we still have a long way to go. I agree to start creating manual tests to fill the gap of no tests for Web App Manifest.

**Comment by marcoscaceres** [comment]
@Honry agree... but we will have to do manual tests for now :( At least, we can evaluate where we are at with regards to conformance in each spec. 

@Honry, what time zone are you in?

**Comment by marcoscaceres** [comment]
fixed typo above.

**Comment by Honry** [comment]
@marcoscaceres, UTC+08:00

**Comment by tomayac** [comment]
I’d be happy to help, but am attending a conference (The Web Conf, Lyon, France) all week. If you plan on ultimately having automated tests, I’m not that sure it’s “pretty straight forward”, but manual tests would get the job done for now. Albeit would be a multistep test, when you focus on `"scope"` etc.

**Comment by tomayac** [comment]
Maybe for now just listing test approaches for the various manifest properties would be enough. Happy to get this going, but quite limited timewise this week.

**Comment by marcoscaceres** [comment]
@tomayac, maybe you could help us with review? I can make add you to the OWNERs over on WPT. That way, we can distribute the workload a little bit more. 

I'd like to look at a bit more at the [research](https://medium.com/@firt/progressive-web-apps-on-ios-are-here-d00430dee3a7) @firtman has done in this area. I recall he found some pretty significant interop issues, which we need to make sure we expose.

**Comment by tomayac** [comment]
SGTM!

**Comment by mgiuca** [comment]
I'm interested. Of course, this fits into the bucket where it's very hard to even define manual tests, because of the user interface being so user-agent-defined. I'm also travelling this week (UTC-7). Next week is better for VC but I'll also be free today from 9am to 11am Melbourne time.

**Comment by marcoscaceres** [comment]
@mgiuca, ok, let's wait till next week as we are in the same timezone. That also makes it easy to sync with @Honry.

**Comment by Honry** [comment]
@marcoscaceres, seems it's a bit difficult to find an appropriate time slot to involve all interested folks in a call. How about just paste you ideas here, then we can discuss and move this forward?

**Comment by Honry** [comment]
@marcoscaceres, soft ping. :)

**Comment by patrickkettner** [comment]
👋 gonna start writing some of these tests in the near future, hopefully @Honry could check it out if I get it in soon?

**Comment by marcoscaceres** [comment]
@Honry, if you could help review or create tests with @patrickkettner it would be awesome. The plan is basically just to make little tests for each manifest property:

So, a HTML file:
```HTML
<doctype html>
<link rel="manifest" href="manifest-shortname.json"> 
```

And then `manifest-shortname.json`:

```JSON
{
  short_name: "PASS"
}
```

And "add to homescreen"... and having the `short_name` show up would be considered a pass. 

@patrickkettner is going to provide us with a link to where we can put the results... might just be an excel sheet, which we can then generate the tests results from as JSON. 

There are some things we can't really test, like the ARC rating stuff... but we might point to the Microsoft Store as evidence that it's being used.

**Comment by Honry** [comment]
@patrickkettner, looking forward to your tests, and I'd be glad to help review and create more tests.

**Comment by aarongustafson** [comment]
@patrickkettner I started writing tests if you’re still willing/able to help: https://github.com/web-platform-tests/wpt/pull/23816

**Comment by marcoscaceres** [comment]
We have a spreadsheet with tests and results so far:
https://docs.google.com/spreadsheets/d/1_Ts5r4WksveBivvQ_KjdBrSDHDmNpNWqiER019A1onM/edit?usp=sharing

**Comment by marcoscaceres** [comment]
Manual tests PR https://github.com/web-platform-tests/wpt/pull/24146

**Comment by aarongustafson** [comment]
@annevk has requested additional tests https://github.com/whatwg/html/pull/5581#pullrequestreview-439224722

**Comment by marcoscaceres** [comment]
Test plan for whatwg/html#5581 is at https://github.com/web-platform-tests/wpt/issues/24389

**Comment by christianliebel** [comment]
# Checklist

**Tested:**
- [x] display
- [x] icons
- [x] name
- [x] orientation
- [x] short_name
- [x] theme_color
- [ ] shortcuts (https://github.com/web-platform-tests/wpt/pull/24452)
- [ ] scope
- [ ] start_url
- [ ] dir
- [ ] lang

**Not testing for now:**
- [ ] description (moves to Manifest App Info, #876)
- [ ] categories (moves to Manifest App Info, #876)
- [ ] screenshots (moves to Manifest App Info, #876)
- [ ] iarc_rating_id (moves to Manifest App Info, #876)
- [ ] related_applications (currently single-engine, #877)
- [ ] prefer_related_applications (currently single-engine, #877)
- [ ] icons/monochrome purpose (currently single-engine, #905)

**Comment by marcoscaceres** [comment]
@christianliebel I deleted your checklist and moved it to the very top. Thanks for creating it!

**Comment by TaTaRsKiY059** [comment]
Update

**Comment by TaTaRsKiY059** [comment]
Update

**Comment by aarongustafson** [comment]
@christianliebel It’s been a while since we last touched this. Can we set up a sync and sort out what & how we want to test the remaining items? I am carving out a few hours a week to try to get back on top of a bunch of this stuff.

**Comment by christianliebel** [comment]
@aarongustafson Sure, let's follow up on Twitter.

**Comment by aarongustafson** [comment]
From our call today:

* @christianliebel to look at CORS & CSP for icons & shortcut icons.
* `scope` is ill-defined & hard to test. Could we test to see if DevTools correctly reads the value and call that good?
* @thejohnjansen & I are taking an action item for myself on how to test `dir` and `lang`. If we don’t have a good direction from that, we could we test to see if DevTools, again, correctly reads the value.

I will open the App  Info-related WPT items on that spec, move the related_applications-related items to their own bug (not tied to CR) and add a callout on the monochrome `purpose` thread that a WPT will be required if that gets more implementations.

**Comment by TaTaRsKiY059** [comment]
Set

**Comment by TaTaRsKiY059** [comment]
Update

**Comment by marcoscaceres** [comment]
We did mostly everything here... so closing.
